import models
from database import SessionLocal

def seed():
    db = SessionLocal()

    if db.query(models.Excursion).count() > 0:
        print("Excursions already exist. Skipping seed.")
        db.close()
        return

    excursions = [
        models.Excursion(
            name="Paris – Croazieră pe Sena",
            price=120,
            duration=1,
            guide=False,
            description="Croazieră de 1 oră pe Sena, cu panorame spre Louvre, Notre-Dame și podurile istorice.",
            latitude=48.8584,
            longitude=2.2945,
            rating=4.5,
            reviews_count=2874,
            recommended=True,
        ),
        models.Excursion(
            name="Paris – Louvre: tur cu acces rapid",
            price=260,
            duration=2.5,
            guide=True,
            description="Tur ghidat în Louvre, cu focus pe capodopere (Mona Lisa, Venus de Milo etc.) și intrare rezervată.",
            latitude=48.8606,
            longitude=2.3376,
            rating=4.7,
            reviews_count=912,
            recommended=True,
        ),
        models.Excursion(
            name="Paris – Montmartre & Sacré-Cœur",
            price=150,
            duration=2,
            guide=True,
            description="Montmartre la pas: străduțe, povești despre artiști, belvedere și bazilica Sacré-Cœur.",
            latitude=48.8867,
            longitude=2.3431,
            rating=4.4,
            reviews_count=421,
            recommended=True,
        ),
        models.Excursion(
            name="Paris – Versailles: tur al Palatului & grădinilor",
            price=420,
            duration=6,
            guide=True,
            description="Excursie la Versailles: tur ghidat în palat + timp liber pentru grădini și zona domeniului.",
            latitude=48.8049,
            longitude=2.1204,
            rating=4.2,
            reviews_count=688,
            recommended=False,
        ),
        models.Excursion(
            name="Nice – Vieux Nice, Cours Saleya & Colline du Château",
            price=140,
            duration=2,
            guide=True,
            description="Tur pietonal prin centrul vechi, piața Cours Saleya și puncte de belvedere spre Promenade des Anglais.",
            latitude=43.6978,
            longitude=7.2759,
            rating=4.3,
            reviews_count=238,
            recommended=True,
        ),
        models.Excursion(
            name="Din Nice – Monaco, Monte-Carlo & Èze",
            price=390,
            duration=9,
            guide=True,
            description="Zi pe Riviera: Èze (sat cocoțat) + Monaco/Monte-Carlo (circuit, port, cazinou) cu opriri panoramice.",
            latitude=43.7384,
            longitude=7.4246,
            rating=4.6,
            reviews_count=1105,
            recommended=True,
        ),

        models.Excursion(
            name="Lyon – Vieux Lyon & Traboules",
            price=170,
            duration=2,
            guide=True,
            description="Explorare ghidată prin Vieux Lyon și celebrele traboules (pasaje ascunse) + curți renascentiste.",
            latitude=45.7622,
            longitude=4.8276,
            rating=4.7,
            reviews_count=803,
            recommended=True,
        ),
        models.Excursion(
            name="Lyon – Croix-Rousse: cartierul canut-ilor & street art",
            price=160,
            duration=2.5,
            guide=True,
            description="Tur în Croix-Rousse: istorie, scări, puncte de belvedere și povești despre canut-i (țesători).",
            latitude=45.7742,
            longitude=4.8279,
            rating=4.2,
            reviews_count=214,
            recommended=False,
        ),
        models.Excursion(
            name="Lyon – Tur culinar tip „bouchon”",
            price=240,
            duration=3,
            guide=True,
            description="Degustări în stil lyonnais (bouchon), opriri la artizani locali + recomandări de gastronomie.",
            latitude=45.7640,
            longitude=4.8357,
            rating=4.5,
            reviews_count=492,
            recommended=True,
        ),
        models.Excursion(
            name="Din Lyon – Beaujolais: tur vinicol",
            price=450,
            duration=5,
            guide=True,
            description="Ieșire în Beaujolais: crame, degustări și sate pitorești, ideal pentru iubitorii de vin.",
            latitude=45.9890,
            longitude=4.7190,
            rating=4.6,
            reviews_count=176,
            recommended=True,
        ),

        models.Excursion(
            name="Marseille – Calanques: tur cu barca",
            price=320,
            duration=3,
            guide=False,
            description="Tur cu barca spre Calanques (peisaje spectaculoase); unele variante includ opriri pentru înot.",
            latitude=43.2135,
            longitude=5.4380,
            rating=4.7,
            reviews_count=1642,
            recommended=True,
        ),
        models.Excursion(
            name="Marseille – Le Panier & Vieux-Port: tur pietonal cu ghid",
            price=150,
            duration=2,
            guide=True,
            description="Cartierul istoric Le Panier: străduțe colorate, viewpoint-uri, povești locale + zona Vieux-Port.",
            latitude=43.3004,
            longitude=5.3698,
            rating=4.2,
            reviews_count=309,
            recommended=True,
        ),
        models.Excursion(
            name="Marseille – Notre-Dame de la Garde & panorame",
            price=130,
            duration=1.5,
            guide=True,
            description="Urcare la basilica Notre-Dame de la Garde pentru panorame + context istoric și foto-stops.",
            latitude=43.2841,
            longitude=5.3710,
            rating=4.4,
            reviews_count=522,
            recommended=False,
        ),
        models.Excursion(
            name="Marseille – Frioul & Château d’If: croazieră/catamaran",
            price=380,
            duration=4,
            guide=False,
            description="Plimbare pe mare către Frioul & Château d’If, cu opriri pentru relaxare și priveliști spre coastă.",
            latitude=43.2804,
            longitude=5.3259,
            rating=4.6,
            reviews_count=741,
            recommended=True,
        ),

        models.Excursion(
            name="Bordeaux – Croazieră pe Garonne cu vin & canelé",
            price=180,
            duration=1.5,
            guide=False,
            description="Croazieră de descoperire pe Garonne, cu un pahar de vin și desert local (canelé).",
            latitude=44.8467,
            longitude=-0.5715,
            rating=4.3,
            reviews_count=612,
            recommended=True,
        ),
        models.Excursion(
            name="Din Bordeaux – Saint-Émilion: tur vinicol + sat medieval",
            price=520,
            duration=7,
            guide=True,
            description="Zi în Saint-Émilion: sat medieval + vizite la crame și degustări (stil „Grand Cru”).",
            latitude=44.8940,
            longitude=-0.1550,
            rating=4.7,
            reviews_count=984,
            recommended=True,
        ),

        models.Excursion(
            name="Toulouse – Vizită Airbus",
            price=260,
            duration=2,
            guide=True,
            description="Tur organizat la facilitățile Airbus din Toulouse (zonă Blagnac), cu explicații despre producție.",
            latitude=43.6350,
            longitude=1.3670,
            rating=4.5,
            reviews_count=418,
            recommended=True,
        ),
        models.Excursion(
            name="Toulouse – Croazieră pe Canal du Midi",
            price=140,
            duration=1.25,
            guide=False,
            description="Croazieră relaxantă pe Canal du Midi, trecând prin ecluzele din zona centrală.",
            latitude=43.6119,
            longitude=1.4330,
            rating=4.2,
            reviews_count=207,
            recommended=False,
        ),
        models.Excursion(
            name="Din Toulouse – Carcassonne: excursie de o zi",
            price=360,
            duration=8,
            guide=False,
            description="Transfer din Toulouse + timp de explorare în Cité de Carcassonne (castel, bastioane, bazilică).",
            latitude=43.2060,
            longitude=2.3630,
            rating=4.6,
            reviews_count=1188,
            recommended=True,
        ),
        models.Excursion(
            name="Din Toulouse – Albi & Cordes-sur-Ciel: day trip",
            price=410,
            duration=8,
            guide=True,
            description="Albi (catedrală și centru vechi) + Cordes-sur-Ciel (sat cocoțat, străduțe medievale).",
            latitude=43.9298,
            longitude=2.1480,
            rating=4.4,
            reviews_count=264,
            recommended=True,
        ),

        models.Excursion(
            name="Cannes – Insula Sainte-Marguerite: ferry + Fort Royal",
            price=160,
            duration=4,
            guide=False,
            description="Bilet ferry dus-întors spre Sainte-Marguerite: plaje, pădure, Fort Royal și zone de relaxare.",
            latitude=43.5198,
            longitude=7.0469,
            rating=4.6,
            reviews_count=955,
            recommended=True,
        ),
        models.Excursion(
            name="Din Cannes – Riviera highlights: Antibes + Saint-Paul-de-Vence",
            price=420,
            duration=6,
            guide=True,
            description="Tur de jumătate/zi pe Riviera: Antibes (vechiul port) + Saint-Paul-de-Vence (sat artistic).",
            latitude=43.6950,
            longitude=7.1220,
            rating=4.3,
            reviews_count=339,
            recommended=True,
        ),

        models.Excursion(
            name="Strasbourg – Catedrala & Petite France: walking tour cu ghid local",
            price=150,
            duration=2,
            guide=True,
            description="Tur prin Grande Île: Catedrală, străduțe pietonale și cartierul Petite France.",
            latitude=48.5817,
            longitude=7.7506,
            rating=4.7,
            reviews_count=501,
            recommended=True,
        ),
        models.Excursion(
            name="Din Strasbourg – Ruta Vinului din Alsacia: degustări",
            price=480,
            duration=5,
            guide=True,
            description="Half-day pe Alsace Wine Route: opriri la 2 crame + degustări și sate tipice alsaciene.",
            latitude=48.4630,
            longitude=7.4810,
            rating=4.8,
            reviews_count=344,
            recommended=True,
        ),

    models.Excursion(
        name="Roma – Colosseum și Forumul Roman",
        price=290,
        duration=3,
        guide=True,
        description="Tur complet în Roma Antică: Colosseum, Forumul Roman și Dealul Palatin, cu intrare rezervată.",
        latitude=41.8902,
        longitude=12.4922,
        rating=4.8,
        reviews_count=2314,
        recommended=True,
    ),
    models.Excursion(
        name="Roma – Muzeele Vaticanului și Capela Sixtină",
        price=320,
        duration=2.5,
        guide=True,
        description="Vizită la Vatican Museums și Capela Sixtină, cu focus pe reperele principale.",
        latitude=41.9065,
        longitude=12.4536,
        rating=4.6,
        reviews_count=1542,
        recommended=True,
    ),
    models.Excursion(
        name="Roma – Trastevere street food",
        price=260,
        duration=3,
        guide=True,
        description="Tur culinar în Trastevere cu degustări de specialități romane și povești locale.",
        latitude=41.8897,
        longitude=12.4708,
        rating=4.4,
        reviews_count=621,
        recommended=True,
    ),
    models.Excursion(
        name="Din Roma – Tivoli și Villa d’Este",
        price=520,
        duration=8,
        guide=True,
        description="Excursie de o zi la Tivoli: Villa d’Este și Villa Adriana, grădini și fântâni spectaculoase.",
        latitude=41.9639,
        longitude=12.7964,
        rating=4.5,
        reviews_count=388,
        recommended=True,
    ),

    models.Excursion(
        name="Veneția – Plimbare cu gondola",
        price=180,
        duration=0.5,
        guide=False,
        description="Plimbare clasică cu gondola prin canale mici și porțiuni din Canal Grande.",
        latitude=45.4370,
        longitude=12.3358,
        rating=4.2,
        reviews_count=2190,
        recommended=True,
    ),
    models.Excursion(
        name="Veneția – Palatul Dogilor și San Marco",
        price=360,
        duration=3,
        guide=True,
        description="Vizită la Palatul Dogilor și Bazilica San Marco, în inima Veneției.",
        latitude=45.4340,
        longitude=12.3399,
        rating=4.7,
        reviews_count=1048,
        recommended=True,
    ),
    models.Excursion(
        name="Din Veneția – Murano și Burano",
        price=320,
        duration=6,
        guide=True,
        description="Tur în lagună: Murano, Burano și opriri pentru descoperirea tradițiilor locale.",
        latitude=45.4408,
        longitude=12.3155,
        rating=4.5,
        reviews_count=1331,
        recommended=True,
    ),
    models.Excursion(
        name="Veneția – Cannaregio și Ghetoul Evreiesc",
        price=170,
        duration=2,
        guide=True,
        description="Tur prin Cannaregio și Ghetoul Evreiesc, cu istorie și povești locale.",
        latitude=45.4469,
        longitude=12.3266,
        rating=4.4,
        reviews_count=206,
        recommended=False,
    ),

    models.Excursion(
        name="Florența – Galeria Uffizi",
        price=280,
        duration=2,
        guide=True,
        description="Vizită la Uffizi, cu capodopere renascentiste și explicații despre artiștii principali.",
        latitude=43.7687,
        longitude=11.2550,
        rating=4.7,
        reviews_count=913,
        recommended=True,
    ),
    models.Excursion(
        name="Florența – David la Accademia",
        price=240,
        duration=1.5,
        guide=True,
        description="Tur la Accademia cu focus pe David și sculpturile lui Michelangelo.",
        latitude=43.7761,
        longitude=11.2587,
        rating=4.8,
        reviews_count=702,
        recommended=True,
    ),
    models.Excursion(
        name="Florența – Duomo și Cupola",
        price=330,
        duration=2.5,
        guide=True,
        description="Tur în zona Duomo și urcare pe cupolă pentru panorame peste Florența.",
        latitude=43.7731,
        longitude=11.2560,
        rating=4.6,
        reviews_count=344,
        recommended=True,
    ),
    models.Excursion(
        name="Din Florența – Chianti wine tour",
        price=420,
        duration=5,
        guide=True,
        description="Excursie în Chianti cu vizite la crame, degustări și peisaje de Toscana.",
        latitude=43.5850,
        longitude=11.3157,
        rating=4.5,
        reviews_count=511,
        recommended=True,
    ),

    models.Excursion(
        name="Milano – Duomo și Terasele",
        price=300,
        duration=2,
        guide=True,
        description="Vizită la Duomo și urcare pe terase pentru panorame peste oraș.",
        latitude=45.4642,
        longitude=9.1916,
        rating=4.6,
        reviews_count=889,
        recommended=True,
    ),
    models.Excursion(
        name="Milano – Cina cea de Taină",
        price=420,
        duration=1,
        guide=True,
        description="Vizită la faimoasa lucrare a lui Leonardo, cu acces pe bază de rezervare.",
        latitude=45.4656,
        longitude=9.1706,
        rating=4.7,
        reviews_count=734,
        recommended=True,
    ),
    models.Excursion(
        name="Milano – Navigli seara",
        price=230,
        duration=2.5,
        guide=True,
        description="Plimbare în Navigli cu opriri pentru aperitivo și gustări, atmosferă locală de seară.",
        latitude=45.4514,
        longitude=9.1770,
        rating=4.3,
        reviews_count=302,
        recommended=False,
    ),
    models.Excursion(
        name="Din Milano – Lacul Como",
        price=520,
        duration=10,
        guide=True,
        description="Excursie de o zi la Lacul Como, cu timp de explorare și viewpoint-uri spectaculoase.",
        latitude=45.8081,
        longitude=9.0852,
        rating=4.6,
        reviews_count=477,
        recommended=True,
    ),

    models.Excursion(
        name="Din Napoli – Pompei și Vezuviu",
        price=450,
        duration=8,
        guide=True,
        description="Excursie de o zi la Pompei și zona Vezuviului, cu opriri pentru panorame peste Golf.",
        latitude=40.7485,
        longitude=14.4840,
        rating=4.5,
        reviews_count=1510,
        recommended=True,
    ),
    models.Excursion(
        name="Napoli Sotterranea",
        price=180,
        duration=1.5,
        guide=True,
        description="Explorare a tunelurilor și cisternei sub centrul istoric, cu povești despre oraș.",
        latitude=40.8527,
        longitude=14.2586,
        rating=4.6,
        reviews_count=804,
        recommended=True,
    ),
    models.Excursion(
        name="Napoli – Street food",
        price=220,
        duration=2.5,
        guide=True,
        description="Tur culinar prin centrul vechi, cu degustări de pizza și patiserie locală.",
        latitude=40.8517,
        longitude=14.2583,
        rating=4.4,
        reviews_count=689,
        recommended=True,
    ),
    models.Excursion(
        name="Napoli – Capri",
        price=540,
        duration=9,
        guide=False,
        description="Excursie la Capri cu transport dus-întors și timp liber pentru explorarea insulei.",
        latitude=40.5507,
        longitude=14.2423,
        rating=4.3,
        reviews_count=412,
        recommended=True,
    ),

    models.Excursion(
        name="Pisa – Turnul Înclinat și Piazza dei Miracoli",
        price=160,
        duration=1.5,
        guide=True,
        description="Vizită la Piazza dei Miracoli: Catedrală, Baptisteriu și zona Turnului Înclinat.",
        latitude=43.7230,
        longitude=10.3966,
        rating=4.5,
        reviews_count=533,
        recommended=True,
    ),
    models.Excursion(
        name="Din Pisa – Cinque Terre",
        price=520,
        duration=10,
        guide=True,
        description="Excursie de o zi la Cinque Terre, cu sate de coastă și viewpoint-uri pentru fotografii.",
        latitude=44.0990,
        longitude=9.7370,
        rating=4.6,
        reviews_count=246,
        recommended=True,
    ),

    models.Excursion(
        name="Verona – Arena și Casa Julietei",
        price=190,
        duration=3,
        guide=True,
        description="Tur în centrul vechi: Arena, Casa Julietei și principalele piețe istorice din Verona.",
        latitude=45.4384,
        longitude=10.9940,
        rating=4.4,
        reviews_count=372,
        recommended=True,
    ),
    models.Excursion(
        name="Din Verona – Lacul Garda",
        price=390,
        duration=8,
        guide=True,
        description="Excursie la Lacul Garda cu oprire în Sirmione și timp pentru promenadă și priveliști.",
        latitude=45.4929,
        longitude=10.6140,
        rating=4.6,
        reviews_count=418,
        recommended=True,
    ),

    models.Excursion(
        name="Madrid – Muzeul Prado",
        price=240,
        duration=1.5,
        guide=True,
        description="Tur în Prado cu focus pe lucrările emblematice și contextul istoric al colecțiilor.",
        latitude=40.4138,
        longitude=-3.6921,
        rating=4.7,
        reviews_count=1184,
        recommended=True,
    ),
    models.Excursion(
        name="Madrid – Palatul Regal",
        price=260,
        duration=2,
        guide=True,
        description="Vizită la Palatul Regal și sălile principale, cu povești despre monarhia spaniolă și arhitectură.",
        latitude=40.4179,
        longitude=-3.7143,
        rating=4.6,
        reviews_count=902,
        recommended=True,
    ),
    models.Excursion(
        name="Madrid – Tapas și centrul vechi",
        price=210,
        duration=3,
        guide=True,
        description="Tur gastronomic prin zonele celebre din centru, cu opriri pentru tapas și băuturi locale.",
        latitude=40.4154,
        longitude=-3.7074,
        rating=4.4,
        reviews_count=511,
        recommended=True,
    ),
    models.Excursion(
        name="Din Madrid – Toledo",
        price=480,
        duration=8,
        guide=True,
        description="Excursie de o zi la Toledo: centru istoric, belvederi și timp pentru explorare pe cont propriu.",
        latitude=39.8628,
        longitude=-4.0273,
        rating=4.5,
        reviews_count=733,
        recommended=True,
    ),

    models.Excursion(
        name="Barcelona – Sagrada Familia",
        price=320,
        duration=1.5,
        guide=True,
        description="Vizită la Sagrada Familia cu explicații despre Gaudí, simboluri și arhitectura basilicii.",
        latitude=41.4036,
        longitude=2.1744,
        rating=4.8,
        reviews_count=1652,
        recommended=True,
    ),
    models.Excursion(
        name="Barcelona – Park Güell",
        price=260,
        duration=1.5,
        guide=True,
        description="Tur în Park Güell: puncte iconice, mozaicuri și viewpoint-uri asupra orașului.",
        latitude=41.4145,
        longitude=2.1527,
        rating=4.6,
        reviews_count=1041,
        recommended=True,
    ),
    models.Excursion(
        name="Din Barcelona – Montserrat",
        price=420,
        duration=6,
        guide=False,
        description="Excursie la Montserrat: mănăstirea, trasee scurte și panorame spectaculoase.",
        latitude=41.5933,
        longitude=1.8382,
        rating=4.5,
        reviews_count=889,
        recommended=True,
    ),
    models.Excursion(
        name="Barcelona – Cartierul Gotic",
        price=160,
        duration=2,
        guide=True,
        description="Plimbare prin Cartierul Gotic și zonele istorice, cu opriri la piețe și străduțe emblematice.",
        latitude=41.3839,
        longitude=2.1760,
        rating=4.3,
        reviews_count=372,
        recommended=False,
    ),

    models.Excursion(
        name="Valencia – Orașul Artelor și Științelor",
        price=240,
        duration=2.5,
        guide=True,
        description="Tur în complexul modern al Valenciei, cu reperele principale și povestea arhitecturii sale.",
        latitude=39.4542,
        longitude=-0.3522,
        rating=4.6,
        reviews_count=640,
        recommended=True,
    ),
    models.Excursion(
        name="Valencia – Albufera la apus",
        price=220,
        duration=4,
        guide=True,
        description="Excursie în Parcul Natural Albufera: plimbare și tur cu barca la apus pe lagună.",
        latitude=39.3356,
        longitude=-0.3346,
        rating=4.7,
        reviews_count=412,
        recommended=True,
    ),
    models.Excursion(
        name="Valencia – Curs de paella",
        price=260,
        duration=4,
        guide=True,
        description="Curs practic de paella cu ingrediente locale și degustare, cu vizită la piață în funcție de program.",
        latitude=39.4745,
        longitude=-0.3769,
        rating=4.5,
        reviews_count=528,
        recommended=True,
    ),
    models.Excursion(
        name="Valencia – Centrul vechi și Catedrala",
        price=150,
        duration=2,
        guide=True,
        description="Tur în centrul vechi: piațe, străzi istorice și zona Catedralei, cu povești despre oraș.",
        latitude=39.4753,
        longitude=-0.3757,
        rating=4.2,
        reviews_count=301,
        recommended=False,
    ),

    models.Excursion(
        name="Sevilla – Alcázar și Catedrala",
        price=300,
        duration=3,
        guide=True,
        description="Vizită la Alcázar și Catedrală, cu reperele principale și contextul istoric al orașului.",
        latitude=37.3830,
        longitude=-5.9911,
        rating=4.8,
        reviews_count=1288,
        recommended=True,
    ),
    models.Excursion(
        name="Sevilla – Flamenco",
        price=200,
        duration=2,
        guide=False,
        description="Seară de flamenco într-un loc dedicat, cu atmosferă autentică și opțiuni de băuturi.",
        latitude=37.3861,
        longitude=-5.9935,
        rating=4.4,
        reviews_count=907,
        recommended=True,
    ),
    models.Excursion(
        name="Sevilla – Barrio Santa Cruz",
        price=150,
        duration=2,
        guide=True,
        description="Plimbare ghidată prin Santa Cruz: străduțe, patios și povești despre Sevilla veche.",
        latitude=37.3862,
        longitude=-5.9903,
        rating=4.3,
        reviews_count=356,
        recommended=False,
    ),
    models.Excursion(
        name="Din Sevilla – Córdoba",
        price=520,
        duration=10,
        guide=True,
        description="Excursie de o zi la Córdoba: Mezquita și centrul istoric, cu timp de explorare.",
        latitude=37.8790,
        longitude=-4.7794,
        rating=4.5,
        reviews_count=494,
        recommended=True,
    ),

    models.Excursion(
        name="Granada – Alhambra",
        price=360,
        duration=3,
        guide=True,
        description="Vizită la Alhambra și grădinile Generalife, cu reperele principale și context istoric.",
        latitude=37.1761,
        longitude=-3.5881,
        rating=4.8,
        reviews_count=1411,
        recommended=True,
    ),
    models.Excursion(
        name="Granada – Albaicín și belvederi",
        price=160,
        duration=2.5,
        guide=True,
        description="Tur în Albaicín, cu viewpoint-uri celebre și străduțe tradiționale, ideal pentru fotografii.",
        latitude=37.1810,
        longitude=-3.5922,
        rating=4.4,
        reviews_count=308,
        recommended=True,
    ),

    models.Excursion(
        name="Bilbao – Muzeul Guggenheim",
        price=240,
        duration=2,
        guide=True,
        description="Tur în Guggenheim Bilbao, cu arhitectură, lucrări emblematice și colecții contemporane.",
        latitude=43.2687,
        longitude=-2.9340,
        rating=4.7,
        reviews_count=972,
        recommended=True,
    ),
    models.Excursion(
        name="Bilbao – Pintxos în orașul vechi",
        price=220,
        duration=3.5,
        guide=True,
        description="Tur culinar cu pintxos în Casco Viejo, cu opriri în baruri tradiționale și degustări.",
        latitude=43.2589,
        longitude=-2.9234,
        rating=4.5,
        reviews_count=611,
        recommended=True,
    ),

        models.Excursion(
            name="Berlin – Reichstag și cupola",
            price=180,
            duration=2.5,
            guide=True,
            description="Tur în zona guvernamentală și vizită la cupola Reichstagului, cu panorame peste Berlin.",
            latitude=52.5186,
            longitude=13.3762,
            rating=4.6,
            reviews_count=1240,
            recommended=True,
        ),
        models.Excursion(
            name="Berlin – Poarta Brandenburg și centrul vechi",
            price=160,
            duration=2,
            guide=True,
            description="Plimbare prin reperele centrale ale Berlinului, cu opriri pentru istorie și fotografie.",
            latitude=52.5163,
            longitude=13.3777,
            rating=4.3,
            reviews_count=612,
            recommended=False,
        ),
        models.Excursion(
            name="Berlin – Insula Muzeelor",
            price=220,
            duration=2.5,
            guide=True,
            description="Tur în zona Insulei Muzeelor cu context istoric și reperele arhitecturale principale.",
            latitude=52.5169,
            longitude=13.4010,
            rating=4.5,
            reviews_count=508,
            recommended=True,
        ),
        models.Excursion(
            name="Din Berlin – Potsdam și Sanssouci",
            price=520,
            duration=7,
            guide=True,
            description="Excursie de o zi la Potsdam: palatul Sanssouci, grădini și zonele cele mai cunoscute.",
            latitude=52.4044,
            longitude=13.0384,
            rating=4.6,
            reviews_count=441,
            recommended=True,
        ),

        models.Excursion(
            name="Munich – Centrul vechi și Marienplatz",
            price=170,
            duration=2,
            guide=True,
            description="Tur pietonal prin centrul istoric: Marienplatz și reperele principale ale orașului.",
            latitude=48.1371,
            longitude=11.5754,
            rating=4.4,
            reviews_count=733,
            recommended=True,
        ),
        models.Excursion(
            name="Munich – BMW Welt și BMW Museum",
            price=240,
            duration=2.5,
            guide=True,
            description="Vizită la complexul BMW, cu focus pe istoria brandului și expozițiile auto.",
            latitude=48.1769,
            longitude=11.5560,
            rating=4.5,
            reviews_count=692,
            recommended=True,
        ),
        models.Excursion(
            name="Din Munich – Neuschwanstein",
            price=590,
            duration=10,
            guide=True,
            description="Excursie de o zi la castelul Neuschwanstein, cu opriri panoramice și timp de vizitare.",
            latitude=47.5576,
            longitude=10.7498,
            rating=4.6,
            reviews_count=1188,
            recommended=True,
        ),
        models.Excursion(
            name="Din Munich – Dachau",
            price=320,
            duration=5,
            guide=True,
            description="Vizită la memorialul Dachau, cu explicații istorice și timp pentru reflecție.",
            latitude=48.2580,
            longitude=11.4340,
            rating=4.4,
            reviews_count=804,
            recommended=True,
        ),

        models.Excursion(
            name="Hamburg – Croazieră în port",
            price=160,
            duration=1,
            guide=False,
            description="Croazieră prin portul Hamburg, cu panorame spre docuri și zona de containere.",
            latitude=53.5461,
            longitude=9.9661,
            rating=4.5,
            reviews_count=1523,
            recommended=True,
        ),
        models.Excursion(
            name="Hamburg – Speicherstadt și HafenCity",
            price=190,
            duration=2.5,
            guide=True,
            description="Tur prin Speicherstadt și HafenCity, cu opriri la puncte iconice și povești locale.",
            latitude=53.5435,
            longitude=9.9880,
            rating=4.6,
            reviews_count=677,
            recommended=True,
        ),
        models.Excursion(
            name="Hamburg – Elbphilharmonie",
            price=180,
            duration=1.5,
            guide=True,
            description="Vizită la Elbphilharmonie și zona din jur, cu belvedere spre port și oraș.",
            latitude=53.5413,
            longitude=9.9841,
            rating=4.4,
            reviews_count=931,
            recommended=True,
        ),
        models.Excursion(
            name="Hamburg – St Pauli și Reeperbahn",
            price=170,
            duration=2,
            guide=True,
            description="Tur de seară în St Pauli, cu povești despre cartier și locuri celebre.",
            latitude=53.5498,
            longitude=9.9666,
            rating=4.2,
            reviews_count=388,
            recommended=False,
        ),

        models.Excursion(
            name="Frankfurt – Römer și centrul vechi",
            price=160,
            duration=2,
            guide=True,
            description="Tur în zona Römerberg și centrul vechi, cu repere istorice și străzi pietonale.",
            latitude=50.1109,
            longitude=8.6821,
            rating=4.3,
            reviews_count=514,
            recommended=True,
        ),
        models.Excursion(
            name="Frankfurt – Main Tower și skyline",
            price=210,
            duration=1.5,
            guide=True,
            description="Tur în zona financiară și viewpoint la Main Tower pentru panorame peste oraș.",
            latitude=50.1136,
            longitude=8.6720,
            rating=4.4,
            reviews_count=629,
            recommended=True,
        ),
        models.Excursion(
            name="Din Frankfurt – Valea Rinului",
            price=560,
            duration=10,
            guide=True,
            description="Excursie pe Valea Rinului: peisaje, sate pitorești și opriri pentru fotografii.",
            latitude=49.9780,
            longitude=7.9231,
            rating=4.5,
            reviews_count=702,
            recommended=True,
        ),
        models.Excursion(
            name="Din Frankfurt – Heidelberg",
            price=520,
            duration=9,
            guide=True,
            description="Excursie de o zi la Heidelberg: centrul vechi, viewpoint-uri și timp pentru explorare.",
            latitude=49.3988,
            longitude=8.6724,
            rating=4.4,
            reviews_count=466,
            recommended=True,
        ),

        models.Excursion(
            name="Cologne – Catedrala și centrul vechi",
            price=160,
            duration=2,
            guide=True,
            description="Tur în jurul Catedralei din Köln și în centrul vechi, cu repere și povești locale.",
            latitude=50.9413,
            longitude=6.9583,
            rating=4.6,
            reviews_count=1044,
            recommended=True,
        ),
        models.Excursion(
            name="Din Cologne – Croazieră pe Rin",
            price=260,
            duration=3,
            guide=False,
            description="Croazieră pe Rin cu panorame urbane și zone verzi din jurul Kölnului.",
            latitude=50.9375,
            longitude=6.9603,
            rating=4.2,
            reviews_count=588,
            recommended=False,
        ),

        models.Excursion(
            name="Stuttgart – Mercedes Benz Museum",
            price=220,
            duration=2.5,
            guide=True,
            description="Vizită la muzeul Mercedes-Benz, cu expoziții despre istoria auto și modele iconice.",
            latitude=48.7886,
            longitude=9.2320,
            rating=4.6,
            reviews_count=911,
            recommended=True,
        ),
        models.Excursion(
            name="Stuttgart – Porsche Museum",
            price=220,
            duration=2,
            guide=True,
            description="Vizită la Porsche Museum, cu expoziții despre modele legendare și evoluția brandului.",
            latitude=48.8343,
            longitude=9.1520,
            rating=4.5,
            reviews_count=774,
            recommended=True,
        ),

        models.Excursion(
            name="Londra – Tower of London",
            price=420,
            duration=3,
            guide=True,
            description="Vizită la Tower of London și zona Crown Jewels, cu istorie, fortificații și povești celebre.",
            latitude=51.5081,
            longitude=-0.0759,
            rating=4.7,
            reviews_count=1834,
            recommended=True,
        ),
        models.Excursion(
            name="Londra – Croazieră pe Tamisa",
            price=160,
            duration=1,
            guide=False,
            description="Croazieră de sightseeing pe Tamisa pentru panorame cu reperele principale ale Londrei.",
            latitude=51.5007,
            longitude=-0.1246,
            rating=4.4,
            reviews_count=2471,
            recommended=True,
        ),
        models.Excursion(
            name="Londra – British Museum",
            price=220,
            duration=2,
            guide=True,
            description="Tur prin cele mai cunoscute galerii și obiecte emblematice din British Museum.",
            latitude=51.5194,
            longitude=-0.1270,
            rating=4.2,
            reviews_count=862,
            recommended=False,
        ),
        models.Excursion(
            name="Din Londra – Harry Potter Studio",
            price=620,
            duration=6,
            guide=False,
            description="Vizită la studiourile Warner Bros: decoruri, recuzită și zone iconice din filme.",
            latitude=51.6906,
            longitude=-0.4187,
            rating=4.7,
            reviews_count=1299,
            recommended=True,
        ),

        models.Excursion(
            name="Edinburgh – Edinburgh Castle",
            price=280,
            duration=2,
            guide=True,
            description="Vizită la Edinburgh Castle cu reperele principale și viewpoint-uri peste oraș.",
            latitude=55.9486,
            longitude=-3.1999,
            rating=4.6,
            reviews_count=1174,
            recommended=True,
        ),
        models.Excursion(
            name="Din Edinburgh – Loch Ness și Highlands",
            price=520,
            duration=12,
            guide=True,
            description="Excursie de o zi prin Highlands cu opriri panoramice și timp în zona Loch Ness.",
            latitude=57.3229,
            longitude=-4.4244,
            rating=4.5,
            reviews_count=966,
            recommended=True,
        ),

        models.Excursion(
            name="Manchester – Old Trafford",
            price=260,
            duration=1.5,
            guide=True,
            description="Tur pe stadion cu acces în zonele emblematice și muzeul clubului.",
            latitude=53.4631,
            longitude=-2.2913,
            rating=4.6,
            reviews_count=842,
            recommended=True,
        ),
        models.Excursion(
            name="Manchester – National Football Museum",
            price=200,
            duration=2,
            guide=False,
            description="Vizită la muzeul fotbalului, cu expoziții interactive și obiecte istorice.",
            latitude=53.4857,
            longitude=-2.2426,
            rating=4.4,
            reviews_count=514,
            recommended=True,
        ),
        models.Excursion(
            name="Manchester – Croazieră pe canal",
            price=160,
            duration=1,
            guide=False,
            description="Croazieră de sightseeing pe Ship Canal și River Irwell, cu peisaje urbane și istorie industrială.",
            latitude=53.4723,
            longitude=-2.2962,
            rating=4.3,
            reviews_count=721,
            recommended=True,
        ),
        models.Excursion(
            name="Manchester – Northern Quarter",
            price=150,
            duration=2,
            guide=True,
            description="Tur la pas prin Northern Quarter: străzi creative, vibe local și opriri bune de poze.",
            latitude=53.4839,
            longitude=-2.2348,
            rating=4.1,
            reviews_count=244,
            recommended=False,
        ),

        models.Excursion(
            name="Liverpool – Mersey Ferry",
            price=150,
            duration=1,
            guide=False,
            description="Croazieră pe Mersey cu vedere spre waterfront și reperele cele mai cunoscute.",
            latitude=53.4066,
            longitude=-2.9953,
            rating=4.5,
            reviews_count=1127,
            recommended=True,
        ),
        models.Excursion(
            name="Liverpool – Anfield",
            price=290,
            duration=1.5,
            guide=True,
            description="Tur pe stadion și muzeu, cu acces în zonele iconice și povești din istoria clubului.",
            latitude=53.4308,
            longitude=-2.9608,
            rating=4.6,
            reviews_count=903,
            recommended=True,
        ),
        models.Excursion(
            name="Liverpool – The Beatles Story",
            price=240,
            duration=2,
            guide=False,
            description="Experiență muzeală dedicată Beatles, pe waterfront, cu expoziții și memorabilia.",
            latitude=53.4014,
            longitude=-2.9935,
            rating=4.4,
            reviews_count=776,
            recommended=True,
        ),
        models.Excursion(
            name="Liverpool – Old Dock tour",
            price=170,
            duration=1,
            guide=True,
            description="Tur scurt dedicat vechiului doc și poveștii portului, cu context istoric despre oraș.",
            latitude=53.4036,
            longitude=-2.9918,
            rating=4.2,
            reviews_count=188,
            recommended=False,
        ),

        models.Excursion(
            name="Birmingham – Cadbury World",
            price=240,
            duration=3,
            guide=False,
            description="Experiență interactivă în lumea Cadbury, cu zone tematice și istoria ciocolatei.",
            latitude=52.4309,
            longitude=-1.9300,
            rating=4.4,
            reviews_count=684,
            recommended=True,
        ),
        models.Excursion(
            name="Birmingham – SEA LIFE",
            price=220,
            duration=2,
            guide=False,
            description="Vizită la acvariul din Birmingham, cu tunel subacvatic și zone interactive.",
            latitude=52.4794,
            longitude=-1.9111,
            rating=4.2,
            reviews_count=531,
            recommended=False,
        ),
        models.Excursion(
            name="Din Birmingham – Warwick Castle",
            price=520,
            duration=8,
            guide=False,
            description="Excursie la Warwick Castle: fortăreață medievală, spectacole sezoniere și grădini.",
            latitude=52.2794,
            longitude=-1.5857,
            rating=4.6,
            reviews_count=743,
            recommended=True,
        ),
        models.Excursion(
            name="Din Birmingham – Black Country Living Museum",
            price=340,
            duration=5,
            guide=False,
            description="Muzeu în aer liber cu reconstituiri, ateliere și atmosferă din epoca industrială.",
            latitude=52.5145,
            longitude=-2.0867,
            rating=4.5,
            reviews_count=402,
            recommended=True,
        ),

    models.Excursion(
        name="Viena – Palatul Schönbrunn",
        price=320,
        duration=2.5,
        guide=True,
        description="Vizită la palat și grădini, cu reperele principale și istoria dinastiei Habsburg.",
        latitude=48.1845,
        longitude=16.3122,
        rating=4.7,
        reviews_count=1584,
        recommended=True,
    ),
    models.Excursion(
        name="Viena – Hofburg și Sisi Museum",
        price=280,
        duration=2,
        guide=True,
        description="Tur în complexul Hofburg cu apartamentele imperiale și expoziția dedicată împărătesei Elisabeta.",
        latitude=48.2066,
        longitude=16.3656,
        rating=4.6,
        reviews_count=911,
        recommended=True,
    ),
    models.Excursion(
        name="Viena – Concert clasic",
        price=220,
        duration=1.5,
        guide=False,
        description="Seară de muzică clasică vieneză într-o sală cu atmosferă intimă, ideală pentru o experiență autentică.",
        latitude=48.2033,
        longitude=16.3823,
        rating=4.4,
        reviews_count=1327,
        recommended=True,
    ),
    models.Excursion(
        name="Din Viena – Valea Dunării Wachau",
        price=560,
        duration=10,
        guide=True,
        description="Excursie de o zi în Wachau cu opriri în zone panoramice și timp pentru explorare în localități pitorești.",
        latitude=48.2273,
        longitude=15.3310,
        rating=4.5,
        reviews_count=476,
        recommended=True,
    ),

    models.Excursion(
        name="Salzburg – Sound of Music",
        price=320,
        duration=4,
        guide=True,
        description="Tur prin locurile emblematice din Salzburg și împrejurimi asociate cu filmul, cu opriri panoramice.",
        latitude=47.8054,
        longitude=13.0416,
        rating=4.6,
        reviews_count=1021,
        recommended=True,
    ),
    models.Excursion(
        name="Din Salzburg – Hallstatt",
        price=520,
        duration=6,
        guide=True,
        description="Excursie în regiunea lacurilor alpine cu timp în Hallstatt pentru promenadă și fotografii.",
        latitude=47.5611,
        longitude=13.6493,
        rating=4.7,
        reviews_count=884,
        recommended=True,
    ),

    models.Excursion(
        name="Innsbruck – Nordkette",
        price=260,
        duration=3,
        guide=False,
        description="Urcare cu funicularul și telecabina spre puncte de belvedere, cu panorame spre oraș și munți.",
        latitude=47.3017,
        longitude=11.3833,
        rating=4.6,
        reviews_count=1194,
        recommended=True,
    ),
    models.Excursion(
        name="Din Innsbruck – Swarovski Kristallwelten",
        price=240,
        duration=3.5,
        guide=False,
        description="Vizită la complexul din Wattens: instalații artistice, camere tematice și parc pentru plimbare.",
        latitude=47.2933,
        longitude=11.5907,
        rating=4.5,
        reviews_count=903,
        recommended=True,
    ),

    models.Excursion(
        name="Zurich – Old Town și Lindenhof",
        price=170,
        duration=2,
        guide=True,
        description="Tur pietonal prin centrul vechi, cu opriri la Lindenhof și puncte bune pentru panorame și istorie locală.",
        latitude=47.3720,
        longitude=8.5400,
        rating=4.4,
        reviews_count=486,
        recommended=True,
    ),
    models.Excursion(
        name="Zurich – Croazieră pe Lacul Zurich",
        price=160,
        duration=1.5,
        guide=False,
        description="Croazieră pe lac pentru panorame spre oraș și Alpi, ideală pentru relaxare și fotografii.",
        latitude=47.3667,
        longitude=8.5467,
        rating=4.3,
        reviews_count=1032,
        recommended=True,
    ),
    models.Excursion(
        name="Din Zurich – Rhine Falls",
        price=420,
        duration=5,
        guide=True,
        description="Excursie la Cascada Rinului, cu viewpoint-uri și timp pentru plimbare în zona panoramică.",
        latitude=47.6777,
        longitude=8.6158,
        rating=4.6,
        reviews_count=774,
        recommended=True,
    ),
    models.Excursion(
        name="Din Zurich – Mount Titlis",
        price=620,
        duration=10,
        guide=True,
        description="Excursie de o zi la Titlis: telecabine, viewpoint-uri alpine și timp pentru explorare în zonă.",
        latitude=46.7724,
        longitude=8.4376,
        rating=4.7,
        reviews_count=901,
        recommended=True,
    ),

    models.Excursion(
        name="Geneva – Lacul și Jet d’Eau",
        price=160,
        duration=2,
        guide=True,
        description="Tur în zona lacului: Jet d’Eau, promenadă și reperele centrale ale Genevei.",
        latitude=46.2068,
        longitude=6.1471,
        rating=4.3,
        reviews_count=512,
        recommended=True,
    ),
    models.Excursion(
        name="Geneva – Orașul vechi",
        price=150,
        duration=2,
        guide=True,
        description="Plimbare ghidată prin centrul vechi: străzi istorice, viewpoint-uri și povești despre oraș.",
        latitude=46.2019,
        longitude=6.1466,
        rating=4.2,
        reviews_count=231,
        recommended=False,
    ),

    models.Excursion(
        name="Lucerne – Kapellbrücke și centrul vechi",
        price=160,
        duration=2,
        guide=True,
        description="Tur pietonal prin centrul vechi din Lucerna, cu opriri la Kapellbrücke și reperele principale.",
        latitude=47.0516,
        longitude=8.3076,
        rating=4.5,
        reviews_count=604,
        recommended=True,
    ),
    models.Excursion(
        name="Din Lucerne – Mount Pilatus",
        price=520,
        duration=6,
        guide=False,
        description="Excursie la Pilatus cu urcare pe munte și viewpoint-uri spectaculoase asupra lacului și Alpilor.",
        latitude=46.9804,
        longitude=8.2533,
        rating=4.7,
        reviews_count=832,
        recommended=True,
    ),

    models.Excursion(
        name="Interlaken – Harder Kulm",
        price=260,
        duration=3,
        guide=False,
        description="Urcare la Harder Kulm pentru panorame peste Interlaken și lacurile din zonă.",
        latitude=46.6990,
        longitude=7.8450,
        rating=4.6,
        reviews_count=1121,
        recommended=True,
    ),
    models.Excursion(
        name="Din Interlaken – Jungfraujoch",
        price=920,
        duration=8,
        guide=False,
        description="Excursie la Jungfraujoch: peisaje alpine, platforme panoramice și experiență la altitudine.",
        latitude=46.5475,
        longitude=7.9801,
        rating=4.7,
        reviews_count=1644,
        recommended=True,
    ),

    models.Excursion(
        name="Lisabona – Belém",
        price=240,
        duration=2.5,
        guide=True,
        description="Plimbare prin Belém cu opriri la reperele cele mai cunoscute și timp pentru fotografii și povești despre epoca marilor descoperiri.",
        latitude=38.6979,
        longitude=-9.2066,
        rating=4.6,
        reviews_count=1284,
        recommended=True,
    ),
    models.Excursion(
        name="Lisabona – Alfama și viewpoint-uri",
        price=180,
        duration=2.5,
        guide=True,
        description="Tur prin Alfama: străduțe înguste, miradouros și atmosferă autentică, cu opriri pentru panorame peste oraș.",
        latitude=38.7123,
        longitude=-9.1292,
        rating=4.4,
        reviews_count=612,
        recommended=True,
    ),
    models.Excursion(
        name="Din Lisabona – Sintra",
        price=520,
        duration=8,
        guide=True,
        description="Excursie de o zi la Sintra cu palate și grădini spectaculoase, plus timp pentru explorare în oraș.",
        latitude=38.7879,
        longitude=-9.3906,
        rating=4.7,
        reviews_count=1933,
        recommended=True,
    ),
    models.Excursion(
        name="Lisabona – Croazieră pe Tagus",
        price=190,
        duration=2,
        guide=False,
        description="Croazieră de sightseeing pe fluviu, perfectă pentru panorame cu podurile și zona istorică a Lisabonei.",
        latitude=38.6937,
        longitude=-9.2083,
        rating=4.3,
        reviews_count=1451,
        recommended=True,
    ),

    models.Excursion(
        name="Porto – Ribeira și centrul vechi",
        price=180,
        duration=2.5,
        guide=True,
        description="Tur pietonal prin Ribeira și centrul istoric, cu opriri la puncte iconice și povești despre oraș și râu.",
        latitude=41.1406,
        longitude=-8.6110,
        rating=4.5,
        reviews_count=807,
        recommended=True,
    ),
    models.Excursion(
        name="Porto – Livraria Lello și panorama orașului",
        price=260,
        duration=3,
        guide=True,
        description="Tur cu oprire la Livraria Lello și locuri emblematice pentru fotografii, plus recomandări locale pentru restul zilei.",
        latitude=41.1467,
        longitude=-8.6148,
        rating=4.4,
        reviews_count=1193,
        recommended=True,
    ),
    models.Excursion(
        name="Din Porto – Douro Valley",
        price=620,
        duration=10,
        guide=True,
        description="Excursie în Douro Valley cu degustări la crame, peisaje viticole și timp pentru relaxare pe malul râului.",
        latitude=41.1908,
        longitude=-7.5431,
        rating=4.7,
        reviews_count=2062,
        recommended=True,
    ),
    models.Excursion(
        name="Porto – Crame în Vila Nova de Gaia",
        price=220,
        duration=2,
        guide=True,
        description="Vizită la crame de Porto wine în Gaia, cu degustare și explicații despre procesul de producție și maturare.",
        latitude=41.1384,
        longitude=-8.6118,
        rating=4.3,
        reviews_count=944,
        recommended=False,
    ),

    models.Excursion(
        name="Faro – Ria Formosa",
        price=320,
        duration=4,
        guide=True,
        description="Tur cu barca prin Ria Formosa, cu opriri pe insule pentru plajă, plimbare și fotografii.",
        latitude=37.0116,
        longitude=-7.9346,
        rating=4.7,
        reviews_count=812,
        recommended=True,
    ),
    models.Excursion(
        name="Din Faro – Benagil și Praia da Marinha",
        price=420,
        duration=6,
        guide=True,
        description="Excursie pe coastă către Benagil și Praia da Marinha, cu timp pentru viewpoint-uri și relaxare pe plajă.",
        latitude=37.0902,
        longitude=-8.4287,
        rating=4.6,
        reviews_count=704,
        recommended=True,
    ),

    models.Excursion(
        name="Amsterdam – Croazieră pe canale",
        price=180,
        duration=1.5,
        guide=False,
        description="Croazieră pe canale prin zonele cele mai frumoase ale orașului, ideală pentru panorame și fotografii.",
        latitude=52.3740,
        longitude=4.9000,
        rating=4.5,
        reviews_count=2840,
        recommended=True,
    ),
    models.Excursion(
        name="Amsterdam – Rijksmuseum",
        price=260,
        duration=2.5,
        guide=True,
        description="Tur în Rijksmuseum cu focus pe lucrările cele mai cunoscute și contextul Epocii de Aur olandeze.",
        latitude=52.3599,
        longitude=4.8852,
        rating=4.7,
        reviews_count=1311,
        recommended=True,
    ),
    models.Excursion(
        name="Amsterdam – Jordaan și zona Anne Frank",
        price=190,
        duration=2.5,
        guide=True,
        description="Plimbare prin Jordaan și zona istorică din jur, cu povești despre oraș și opriri în locuri fotogenice.",
        latitude=52.3752,
        longitude=4.8839,
        rating=4.3,
        reviews_count=533,
        recommended=False,
    ),
    models.Excursion(
        name="Din Amsterdam – Zaanse Schans",
        price=520,
        duration=7,
        guide=True,
        description="Excursie în Olanda rurală: mori de vânt, demonstrații tradiționale și opriri în sate pitorești.",
        latitude=52.4749,
        longitude=4.8165,
        rating=4.6,
        reviews_count=1644,
        recommended=True,
    ),

    models.Excursion(
        name="Rotterdam – Markthal și Cube Houses",
        price=190,
        duration=2,
        guide=True,
        description="Tur prin arhitectura modernă a orașului, cu opriri la Markthal și Cube Houses, plus viewpoint-uri urbane.",
        latitude=51.9204,
        longitude=4.4901,
        rating=4.5,
        reviews_count=621,
        recommended=True,
    ),
    models.Excursion(
        name="Rotterdam – Croazieră în port",
        price=180,
        duration=1.25,
        guide=False,
        description="Croazieră în port pentru perspective spectaculoase asupra orașului și a zonei maritime.",
        latitude=51.9177,
        longitude=4.4871,
        rating=4.3,
        reviews_count=1188,
        recommended=True,
    ),

    models.Excursion(
        name="Utrecht – Dom Tower",
        price=210,
        duration=1.5,
        guide=True,
        description="Vizită la Dom Tower pentru panorame peste Utrecht, cu explicații despre istoria orașului.",
        latitude=52.0906,
        longitude=5.1210,
        rating=4.6,
        reviews_count=447,
        recommended=True,
    ),
    models.Excursion(
        name="Utrecht – Canale și centrul vechi",
        price=180,
        duration=2,
        guide=False,
        description="Plimbare și vibe local pe lângă canalele istorice, cu opriri în zonele cele mai frumoase din centru.",
        latitude=52.0914,
        longitude=5.1218,
        rating=4.2,
        reviews_count=312,
        recommended=False,
    ),

    models.Excursion(
        name="Bruxelles – Grand Place și centrul vechi",
        price=170,
        duration=2,
        guide=True,
        description="Tur pietonal prin centrul istoric: Grand Place, străduțe celebre și povești despre Bruxelles.",
        latitude=50.8467,
        longitude=4.3525,
        rating=4.5,
        reviews_count=744,
        recommended=True,
    ),
    models.Excursion(
        name="Bruxelles – Atomium",
        price=220,
        duration=2,
        guide=False,
        description="Vizită la Atomium pentru expoziții și panorame, plus timp pentru fotografii în zona Heysel.",
        latitude=50.8950,
        longitude=4.3416,
        rating=4.3,
        reviews_count=1281,
        recommended=True,
    ),
    models.Excursion(
        name="Bruxelles – Tur de bere și ciocolată",
        price=240,
        duration=3,
        guide=True,
        description="Experiență de degustare cu specialități belgiene, opriri în locuri populare și povești locale.",
        latitude=50.8485,
        longitude=4.3510,
        rating=4.6,
        reviews_count=692,
        recommended=True,
    ),
    models.Excursion(
        name="Din Bruxelles – Bruges",
        price=520,
        duration=10,
        guide=True,
        description="Excursie de o zi la Bruges, cu timp pentru plimbare pe canale și explorarea centrului medieval.",
        latitude=51.2093,
        longitude=3.2247,
        rating=4.5,
        reviews_count=1338,
        recommended=True,
    ),

    models.Excursion(
        name="Bruges – Croazieră pe canale",
        price=160,
        duration=1,
        guide=False,
        description="Croazieră clasică pe canalele din Bruges, ideală pentru panorame și fotografii.",
        latitude=51.2089,
        longitude=3.2242,
        rating=4.4,
        reviews_count=1877,
        recommended=True,
    ),
    models.Excursion(
        name="Bruges – Centrul medieval",
        price=170,
        duration=2,
        guide=True,
        description="Tur pietonal prin centrul medieval: piețe, străduțe și reperele cele mai cunoscute ale orașului.",
        latitude=51.2086,
        longitude=3.2262,
        rating=4.3,
        reviews_count=556,
        recommended=True,
    ),

    models.Excursion(
        name="Ghent – Gravensteen și centrul vechi",
        price=170,
        duration=2.5,
        guide=True,
        description="Tur în Ghent cu oprire la Gravensteen și plimbare prin zonele istorice de pe canale.",
        latitude=51.0572,
        longitude=3.7209,
        rating=4.5,
        reviews_count=423,
        recommended=True,
    ),
    models.Excursion(
        name="Ghent – Tur de seară pe canale",
        price=160,
        duration=1.5,
        guide=False,
        description="Croazieră de seară pe canale pentru vedere asupra clădirilor istorice iluminate.",
        latitude=51.0538,
        longitude=3.7223,
        rating=4.2,
        reviews_count=611,
        recommended=False,
    ),

    models.Excursion(
        name="Budapesta – Parlamentul",
        price=240,
        duration=2,
        guide=True,
        description="Vizită la clădirea Parlamentului cu reperele principale și explicații despre istoria Ungariei.",
        latitude=47.5076,
        longitude=19.0457,
        rating=4.7,
        reviews_count=1642,
        recommended=True,
    ),
    models.Excursion(
        name="Budapesta – Băile Széchenyi",
        price=220,
        duration=3,
        guide=False,
        description="Experiență la băile termale Széchenyi, cu timp pentru relaxare în piscinele interioare și exterioare.",
        latitude=47.5186,
        longitude=19.0810,
        rating=4.5,
        reviews_count=2811,
        recommended=True,
    ),
    models.Excursion(
        name="Budapesta – Croazieră pe Dunăre",
        price=180,
        duration=1.5,
        guide=False,
        description="Croazieră pe Dunăre pentru panorame spre poduri și clădirile emblematice ale orașului.",
        latitude=47.4980,
        longitude=19.0402,
        rating=4.4,
        reviews_count=3022,
        recommended=True,
    ),
    models.Excursion(
        name="Budapesta – Castelul Buda și Bastionul Pescarilor",
        price=210,
        duration=2.5,
        guide=True,
        description="Tur în zona Buda: Castelul, Bastionul Pescarilor și viewpoint-uri spre Parlament.",
        latitude=47.4969,
        longitude=19.0399,
        rating=4.6,
        reviews_count=944,
        recommended=True,
    ),

    models.Excursion(
        name="Praga – Orașul vechi",
        price=180,
        duration=2.5,
        guide=True,
        description="Tur în centrul vechi: piețe, străduțe istorice și opriri la reperele cele mai cunoscute.",
        latitude=50.0870,
        longitude=14.4208,
        rating=4.6,
        reviews_count=781,
        recommended=True,
    ),
    models.Excursion(
        name="Praga – Castelul din Praga",
        price=240,
        duration=3,
        guide=True,
        description="Vizită la complexul castelului și zonele principale, cu panorame și povești despre istoria orașului.",
        latitude=50.0909,
        longitude=14.4005,
        rating=4.5,
        reviews_count=1031,
        recommended=True,
    ),

    models.Excursion(
        name="Brno – Vila Tugendhat",
        price=220,
        duration=2,
        guide=True,
        description="Vizită la Vila Tugendhat, cu detalii despre arhitectură modernistă și istoria clădirii.",
        latitude=49.2070,
        longitude=16.6166,
        rating=4.6,
        reviews_count=344,
        recommended=True,
    ),
    models.Excursion(
        name="Din Brno – Castelul Pernštejn",
        price=420,
        duration=6,
        guide=False,
        description="Excursie la Castelul Pernštejn, cu timp pentru vizită și plimbare în împrejurimi.",
        latitude=49.5396,
        longitude=16.3372,
        rating=4.4,
        reviews_count=219,
        recommended=True,
    ),

    models.Excursion(
        name="Varșovia – Orașul vechi",
        price=160,
        duration=2,
        guide=True,
        description="Tur pietonal prin centrul vechi reconstruit, cu opriri la piețe, ziduri și puncte iconice ale orașului.",
        latitude=52.2499,
        longitude=21.0122,
        rating=4.5,
        reviews_count=612,
        recommended=True,
    ),
    models.Excursion(
        name="Varșovia – Palatul Culturii",
        price=190,
        duration=1.5,
        guide=False,
        description="Vizită la Palatul Culturii cu viewpoint pentru panorame peste Varșovia și timp pentru fotografii.",
        latitude=52.2319,
        longitude=21.0067,
        rating=4.2,
        reviews_count=884,
        recommended=False,
    ),
    models.Excursion(
        name="Varșovia – Muzeul Revoltei din 1944",
        price=220,
        duration=2.5,
        guide=True,
        description="Vizită la muzeu cu context despre Revolta din Varșovia, expoziții interactive și povești personale.",
        latitude=52.2327,
        longitude=20.9830,
        rating=4.6,
        reviews_count=721,
        recommended=True,
    ),
    models.Excursion(
        name="Din Varșovia – Palatul Wilanów",
        price=260,
        duration=3,
        guide=False,
        description="Excursie la Palatul Wilanów și grădini, cu timp pentru plimbare și fotografii.",
        latitude=52.1657,
        longitude=21.0906,
        rating=4.4,
        reviews_count=433,
        recommended=True,
    ),

    models.Excursion(
        name="Cracovia – Centrul vechi și Castelul Wawel",
        price=180,
        duration=3,
        guide=True,
        description="Tur prin centrul vechi din Cracovia și zona Wawel, cu povești despre regi și istoria orașului.",
        latitude=50.0548,
        longitude=19.9352,
        rating=4.7,
        reviews_count=942,
        recommended=True,
    ),
    models.Excursion(
        name="Cracovia – Cartierul Evreiesc Kazimierz",
        price=160,
        duration=2.5,
        guide=True,
        description="Tur în Kazimierz cu sinagogi, străduțe istorice și povești despre cultura evreiască din Cracovia.",
        latitude=50.0510,
        longitude=19.9447,
        rating=4.5,
        reviews_count=511,
        recommended=True,
    ),
    models.Excursion(
        name="Din Cracovia – Auschwitz Birkenau",
        price=520,
        duration=7,
        guide=True,
        description="Vizită la Auschwitz-Birkenau cu ghid, cu context istoric și timp pentru reflecție.",
        latitude=50.0359,
        longitude=19.1783,
        rating=4.6,
        reviews_count=1344,
        recommended=True,
    ),
    models.Excursion(
        name="Din Cracovia – Mina de sare Wieliczka",
        price=480,
        duration=5,
        guide=True,
        description="Excursie la mina de sare Wieliczka: galerii subterane, săli sculptate și capele impresionante.",
        latitude=49.9834,
        longitude=20.0553,
        rating=4.7,
        reviews_count=1188,
        recommended=True,
    ),

    models.Excursion(
        name="Zagreb – Orașul vechi",
        price=150,
        duration=2,
        guide=True,
        description="Tur în centrul istoric: Upper Town, piețe și viewpoint-uri, cu povești despre oraș și arhitectură.",
        latitude=45.8150,
        longitude=15.9770,
        rating=4.4,
        reviews_count=344,
        recommended=True,
    ),
    models.Excursion(
        name="Zagreb – Muzeul Relațiilor Frânte",
        price=190,
        duration=1.5,
        guide=False,
        description="Vizită la muzeul faimos din Upper Town, cu expoziții unice și timp pentru explorare.",
        latitude=45.8162,
        longitude=15.9730,
        rating=4.3,
        reviews_count=901,
        recommended=True,
    ),

    models.Excursion(
        name="Dubrovnik – Zidurile orașului",
        price=260,
        duration=2,
        guide=True,
        description="Plimbare pe zidurile Dubrovnikului, cu panorame superbe asupra Adriaticii și a centrului vechi.",
        latitude=42.6409,
        longitude=18.1100,
        rating=4.7,
        reviews_count=1733,
        recommended=True,
    ),
    models.Excursion(
        name="Dubrovnik – Croazieră la apus",
        price=240,
        duration=2,
        guide=False,
        description="Croazieră de seară pentru panorame cu zidurile orașului și insulele din apropiere.",
        latitude=42.6507,
        longitude=18.0944,
        rating=4.5,
        reviews_count=822,
        recommended=True,
    ),
    models.Excursion(
        name="Din Dubrovnik – Lokrum",
        price=190,
        duration=4,
        guide=False,
        description="Excursie pe insula Lokrum: plimbare, plaje, viewpoint-uri și timp de relaxare.",
        latitude=42.6266,
        longitude=18.1214,
        rating=4.4,
        reviews_count=611,
        recommended=True,
    ),
    models.Excursion(
        name="Din Dubrovnik – Elafiti Islands",
        price=420,
        duration=8,
        guide=False,
        description="Tur de o zi spre insulele Elafiti, cu opriri pentru plajă, înot și explorare în sate mici.",
        latitude=42.7220,
        longitude=18.0000,
        rating=4.6,
        reviews_count=702,
        recommended=True,
    ),

    models.Excursion(
        name="Split – Palatul lui Dioclețian",
        price=170,
        duration=2,
        guide=True,
        description="Tur în centrul vechi din Split, cu focus pe Palatul lui Dioclețian și reperele romane.",
        latitude=43.5089,
        longitude=16.4406,
        rating=4.6,
        reviews_count=988,
        recommended=True,
    ),
    models.Excursion(
        name="Split – Croazieră la Blue Lagoon",
        price=420,
        duration=8,
        guide=False,
        description="Tur pe mare cu oprire pentru înot în Blue Lagoon și timp de relaxare pe insule.",
        latitude=43.5081,
        longitude=16.4402,
        rating=4.5,
        reviews_count=1144,
        recommended=True,
    ),
    models.Excursion(
        name="Din Split – Hvar",
        price=520,
        duration=10,
        guide=False,
        description="Excursie de o zi la Hvar, cu timp în oraș și opriri pentru înot și fotografii.",
        latitude=43.1729,
        longitude=16.4424,
        rating=4.6,
        reviews_count=963,
        recommended=True,
    ),
    models.Excursion(
        name="Din Split – Parcul Național Krka",
        price=480,
        duration=10,
        guide=True,
        description="Excursie la Krka pentru cascade și trasee ușoare, cu timp pentru fotografii și plimbare.",
        latitude=43.8050,
        longitude=15.9720,
        rating=4.7,
        reviews_count=1211,
        recommended=True,
    ),

        models.Excursion(
            name="București – Palatul Parlamentului",
            price=260,
            duration=2,
            guide=True,
            description="Vizită în Palatul Parlamentului cu săli reprezentative și povești despre construcția clădirii.",
            latitude=44.4275,
            longitude=26.0871,
            rating=4.6,
            reviews_count=1842,
            recommended=True,
        ),
        models.Excursion(
            name="București – Centrul vechi",
            price=160,
            duration=2.5,
            guide=True,
            description="Tur pietonal prin centrul vechi: străduțe, clădiri istorice și opriri bune pentru poze.",
            latitude=44.4325,
            longitude=26.1027,
            rating=4.3,
            reviews_count=911,
            recommended=True,
        ),
        models.Excursion(
            name="București – Muzeul Satului",
            price=170,
            duration=2.5,
            guide=False,
            description="Plimbare prin muzeul în aer liber cu gospodării tradiționale și zone tematice din diferite regiuni.",
            latitude=44.4766,
            longitude=26.0783,
            rating=4.5,
            reviews_count=642,
            recommended=True,
        ),
        models.Excursion(
            name="Din București – Castelul Mogoșoaia",
            price=240,
            duration=4,
            guide=False,
            description="Ieșire la Mogoșoaia pentru palat, grădini și promenadă pe malul lacului.",
            latitude=44.5312,
            longitude=25.9962,
            rating=4.4,
            reviews_count=533,
            recommended=False,
        ),

        models.Excursion(
            name="Cluj-Napoca – Centrul vechi",
            price=150,
            duration=2,
            guide=True,
            description="Tur prin centrul istoric: piețe, străzi pietonale și reperele cele mai cunoscute ale orașului.",
            latitude=46.7712,
            longitude=23.6236,
            rating=4.4,
            reviews_count=488,
            recommended=True,
        ),
        models.Excursion(
            name="Cluj-Napoca – Grădina Botanică",
            price=160,
            duration=2,
            guide=False,
            description="Vizită la grădina botanică, cu sere, alei și zone tematice pentru relaxare și fotografii.",
            latitude=46.7655,
            longitude=23.5989,
            rating=4.3,
            reviews_count=612,
            recommended=False,
        ),
        models.Excursion(
            name="Din Cluj – Salina Turda",
            price=420,
            duration=5,
            guide=True,
            description="Excursie la Salina Turda, cu timp pentru explorare în subteran și atracțiile principale.",
            latitude=46.5867,
            longitude=23.7876,
            rating=4.7,
            reviews_count=1933,
            recommended=True,
        ),
        models.Excursion(
            name="Din Cluj – Cheile Turzii",
            price=360,
            duration=5,
            guide=False,
            description="Traseu ușor spre mediu prin chei, cu viewpoint-uri și porțiuni spectaculoase pentru poze.",
            latitude=46.5560,
            longitude=23.6976,
            rating=4.6,
            reviews_count=711,
            recommended=True,
        ),

        models.Excursion(
            name="Brașov – Centrul vechi",
            price=160,
            duration=2,
            guide=True,
            description="Tur pietonal prin centrul istoric: Piața Sfatului, străduțe și povești despre oraș.",
            latitude=45.6433,
            longitude=25.5881,
            rating=4.5,
            reviews_count=904,
            recommended=True,
        ),
        models.Excursion(
            name="Brașov – Biserica Neagră",
            price=170,
            duration=1.5,
            guide=False,
            description="Vizită la Biserica Neagră, cu timp pentru interior și zona din jur pentru fotografii.",
            latitude=45.6411,
            longitude=25.5886,
            rating=4.3,
            reviews_count=1331,
            recommended=False,
        ),
        models.Excursion(
            name="Brașov – Tâmpa",
            price=190,
            duration=2.5,
            guide=False,
            description="Urcare pentru panorame peste Brașov și plimbare pe trasee scurte, ideale pentru apus.",
            latitude=45.6389,
            longitude=25.5947,
            rating=4.6,
            reviews_count=812,
            recommended=True,
        ),
        models.Excursion(
            name="Din Brașov – Castelul Bran",
            price=380,
            duration=5,
            guide=True,
            description="Excursie la Bran cu timp pentru vizită și puncte de belvedere din zonă.",
            latitude=45.5156,
            longitude=25.3670,
            rating=4.4,
            reviews_count=1650,
            recommended=True,
        ),

        models.Excursion(
            name="Sibiu – Centrul vechi",
            price=150,
            duration=2,
            guide=True,
            description="Tur în centrul istoric: piețe, pasaje, viewpoint-uri și atmosfera orașului vechi.",
            latitude=45.7988,
            longitude=24.1517,
            rating=4.6,
            reviews_count=644,
            recommended=True,
        ),
        models.Excursion(
            name="Sibiu – Muzeul Astra",
            price=190,
            duration=3,
            guide=False,
            description="Vizită la muzeul în aer liber din Dumbrava Sibiului, cu gospodării tradiționale și alei de plimbare.",
            latitude=45.7692,
            longitude=24.1221,
            rating=4.7,
            reviews_count=521,
            recommended=True,
        ),

        models.Excursion(
            name="Timișoara – Centrul vechi",
            price=150,
            duration=2,
            guide=True,
            description="Tur pietonal prin piețele centrale și reperele istorice, cu povești despre oraș.",
            latitude=45.7566,
            longitude=21.2287,
            rating=4.4,
            reviews_count=433,
            recommended=True,
        ),
        models.Excursion(
            name="Timișoara – Croazieră pe Bega",
            price=160,
            duration=1.5,
            guide=False,
            description="Plimbare pe apă pentru relaxare și panorame urbane, ideală pentru final de zi.",
            latitude=45.7539,
            longitude=21.2267,
            rating=4.2,
            reviews_count=612,
            recommended=False,
        ),
        models.Excursion(
            name="Timișoara – Muzeul Satului Bănățean",
            price=170,
            duration=2.5,
            guide=False,
            description="Vizită la muzeul în aer liber cu gospodării tradiționale și zone de promenadă.",
            latitude=45.7358,
            longitude=21.2662,
            rating=4.3,
            reviews_count=301,
            recommended=False,
        ),
        models.Excursion(
            name="Din Timișoara – Castelul Corvinilor",
            price=520,
            duration=9,
            guide=True,
            description="Excursie de o zi la Castelul Corvinilor, cu timp pentru vizită și fotografii în jurul fortăreței.",
            latitude=45.7546,
            longitude=22.9028,
            rating=4.6,
            reviews_count=988,
            recommended=True,
        ),
    ]

    db.add_all(excursions)
    db.commit()
    db.close()
    print("Seed done: inserted excursions.")

if __name__ == "__main__":
    seed()
